### ISSUE TITLE
Runtime Error even after installed 5.0 

### ISSUE THREAD

**Issue by carnby77** [Nazky/PS22PS4-GUI#1]
keep saying .net runtime not found even when insatlled.Why?
![runtime error](https://user-images.githubusercontent.com/89453256/197432272-a328cebc-09d7-4ef9-89f4-057aab0e2250.JPG)

**Comment by Nazky** [comment]
are you on x64 or x86 ? also try to restart you'r computer

**Comment by carnby77** [comment]
> are you on x64 or x86 ? also try to restart you'r computer

Im on X64 Windows Pro 64 bit

**Comment by Nazky** [comment]
try the new version see if it's fixed

**Comment by carnby77** [comment]
> try the new version see if it's fixed

Nope. Still getting the runtime not installed and then downloading the runtime....

**Comment by Nazky** [comment]
I am going to try to replace the error with a simple warning to be able to run the app without .net 5 until i find what exactly the problem is
