### ISSUE TITLE
Microsoft Defender mark it as a virus...

### ISSUE THREAD

**Issue by gemimmo** [Nazky/PS22PS4-GUI#5]

**Comment by chronoss09** [comment]
![Capture](https://github.com/Nazky/PS22PS4-GUI/assets/17669980/79f26c0c-a6c0-4a30-b2e6-f957d85e8d52)

**Comment by erfg12** [comment]
Same here, I can't use it.

**Comment by Nazky** [comment]
this should be fixed with BETA 7.0

**Comment by chronoss09** [comment]
not yet, it give me something with the last version...

**Comment by Nazky** [comment]
i have try to scan the file and i also test it on virustotal and defender should not mark it as a virus

**Comment by Nazky** [comment]
here is the proof just in case 
![ezgif-5-e7304043bb](https://github.com/Nazky/PS22PS4-GUI/assets/56560636/87f24e2f-7f0e-4843-9afb-32eee6318678)

**Comment by chronoss09** [comment]
ok, i will re-test... thanks !!!
